sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=kotlin:S107
sonar.issue.ignore.multicriteria.e1.resourceKey=**/ui/**/*.kt
sonar.issue.ignore.multicriteria.e2.ruleKey=kotlin:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=**/ui/**/*.kt