sonar.issue.ignore.multicriteria=e1,e2,e3,e4
sonar.issue.ignore.multicriteria.e1.ruleKey=kotlin:S107
sonar.issue.ignore.multicriteria.e1.resourceKey=**/ui/**/*.kt
sonar.issue.ignore.multicriteria.e2.ruleKey=kotlin:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=**/ui/**/*.kt
sonar.issue.ignore.multicriteria.e3.ruleKey=text:S8569
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.kts
sonar.issue.ignore.multicriteria.e4.ruleKey=text:S8569
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.gradle